### ISSUE TITLE
SVM grid search taking hours to run?

### ISSUE THREAD

**Issue by ElizabethBreen** [ElizabethBreen/CSS_Project3_Team2#6]
I'm not sure why, but my SVM grid search is taking hours to complete -- so long that the software hasn't actually completed a grid search successfully (I closed my computer yesterday after ~ 2 hours). Any ideas on how to speed it up? 

I did a correlation grid and removed features with R^2 > 0.70, reducing the # of features to 41 before initiating the search, but perhaps we need to cut it down more? Thanks!

**Comment by Akesari12** [comment]
I suspect it's probably your choice of kernel. With sufficiently complex data, some kernels can take a long time to run because they draw pairwise distances between different points in high dimensions. I would try tuning the other hyperparameters and only use one type of kernel to see if that runs more quickly, and if that doesn't work then let me know!

**Comment by ElizabethBreen** [comment]
Awesome, thanks so much!
